valid_email_regex: \A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z
max_length_name: 50
max_length_email: 255
min_length_password: 8
rails_tutorial: http://www.railstutorial.org/
rails_tutorial_help: http://www.railstutorial.org/help
items_per_page: 10
gravatar_size: 50
show_follow_gravatar_size: 30
email_server: http://gravatar.com/emails
mail_from: noreply@example.com
reset_password_expired_hours: 2
digit_140: 140
digit_50: 50
digit_500: 500
image_types: ["image/jpeg", "image/gif", "image/png"]
image_size: 5
